AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40

Layout/LineLength:
  Max: 200
