AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 200
